// <auto-generated />
using System;
using Juzhen.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdminApi.Migrations
{
    [DbContext(typeof(DefaultIdentityUIDbContext))]
    partial class DefaultIdentityUIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Juzhen.IdentityUI.Domain.IdentityMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MenuIcon")
                        .HasColumnType("longtext");

                    b.Property<int>("MenuLevel")
                        .HasColumnType("int");

                    b.Property<string>("MenuName")
                        .HasColumnType("longtext");

                    b.Property<int>("MenuPid")
                        .HasColumnType("int");

                    b.Property<string>("MenuSort")
                        .HasColumnType("longtext");

                    b.Property<string>("MenuUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("__identity_menu");
                });

            modelBuilder.Entity("Juzhen.IdentityUI.Domain.IdentityRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("__identity_role");
                });

            modelBuilder.Entity("Juzhen.IdentityUI.Domain.IdentityRoleMenus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("__identity_role_menu");
                });

            modelBuilder.Entity("Juzhen.Infrastructure.__IdentityUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .HasColumnType("longtext");

                    b.Property<string>("HeadImg")
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("__identity_user");
                });

            modelBuilder.Entity("Juzhen.IdentityUI.Domain.IdentityRoleMenus", b =>
                {
                    b.HasOne("Juzhen.IdentityUI.Domain.IdentityRole", null)
                        .WithMany("Menus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Juzhen.Infrastructure.__IdentityUser", b =>
                {
                    b.HasOne("Juzhen.IdentityUI.Domain.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Juzhen.IdentityUI.Domain.IdentityRole", b =>
                {
                    b.Navigation("Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
